### PR TITLE
Added: python QueryClient

### PR DESCRIPTION
**Pull request by DmitryBe**
Rationale: Access logged calls from Python to create a dataset for further processing and advanced evaluation.

Example:
```python
from openpipe.query_client import QueryClient, FilterCondition, QueryResponse

client = QueryClient.create()
res: QueryResponse = client.query_logged_calls(
    filters=[
        FilterCondition(field="chain_name", comparator="=", value="classify"),
    ]
)
len(res.calls)
```

### CODE REVIEW

**Comment by corbt** [comment]
Awesome, this is definitely functionality we want to expose through the SDK!

Hang tight though -- we're actually in the middle of swapping out our code-generated Python SDK which will affect this PR. (See https://github.com/OpenPipe/OpenPipe/pull/427).

**Comment by arcticfly** [comment]
@DmitryBe The biggest changes to the API are out of the way. Would you like to fix conflicts and test this route out again?

**Comment by corbt** [comment]
Also, I'm hoping that with our changes to the Python SDK generator, you won't need a separate `QueryClient` anymore? In other words, could this PR be reduced to the API changes and the downstream changes to the code-generated clients?

**Comment by corbt** [comment]
Going to close as there are now significant merge conflicts here.

**Pull request closed without merging**
