### PR TITLE
Add support for Palm, Claude-2, Cohere, Replicate Llama2 CodeLlama, Ollama, (100+LLMs)

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds support for the above mentioned LLMs using LiteLLM https://github.com/BerriAI/litellm/ 
LiteLLM is a lightweight package to simplify LLM API calls - use any llm as a drop in replacement for gpt-3.5-turbo. 

Example
```python
from litellm import completion

## set ENV variables
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion(model="command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
Addressing:
https://github.com/OpenPipe/OpenPipe/issues/194 
https://github.com/OpenPipe/OpenPipe/issues/159 - LiteLLM Caching / LiteLLM also has a GPT cache integration: https://docs.litellm.ai/docs/caching/
https://github.com/OpenPipe/OpenPipe/issues/145, https://github.com/OpenPipe/OpenPipe/issues/144 - LiteLLM returns input/output tokens + pricing for replicate, anthropic
https://github.com/OpenPipe/OpenPipe/issues/229 - Through Ollama, TogetherAI, HuggingFace providers

**Comment by ishaan-jaff** [comment]
@corbt @arcticfly can you take a look a this PR when possible? 

If you'd prefer to discuss how to do this integration over call I'm sharing a link to my [calendly](https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2023-09)  for your convenience

**Comment by corbt** [comment]
Hey @ishaan-jaff, thanks for the PR. LiteLLM looks really cool! I haven't looked into your service too deeply yet, but one initial concern I have is that it would be pretty confusing if our Typescript and Python SDKs don't behave the same way / support the same models. Do you support Typescript as well?

**Comment by ghost** [comment]
Hey @corbt unfortunately not yet :(

**Comment by corbt** [comment]
Ok given that let's go ahead and pause this until it's something that'll work across the board.

**Pull request closed without merging**
